version: '2.1'
services:
  ldap:
    image: osixia/openldap:1.4.0
    container_name: ldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Mind-Hochschul-Netzwerk"
      LDAP_DOMAIN: "mind-hochschul-netzwerk.de"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    volumes:
      - ./docker/volumes/ldap:/var/lib/ldap
      - ./docker/volumes/slapd.d:/etc/ldap/slapd.d
    ports:
      - "389:389"
    networks:
      - backend
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - ldap
    networks:
      - backend
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpldapadmin.rule=Host(`pla.docker.localhost`)
networks:
  backend:
    name: backend
  traefik:
    name: traefik
