version: "3.5"
services:
  ldap:
    image: osixia/openldap:1.4.0
    container_name: ldap
    restart: unless-stopped
    environment:
      - LDAP_LOG_LEVEL=256
      - LDAP_ORGANISATION=Mind-Hochschul-Netzwerk
      - LDAP_DOMAIN=mind-hochschul-netzwerk.de
      - LDAP_BASE_DN=
      - LDAP_ADMIN_PASSWORD
      - LDAP_CONFIG_PASSWORD
      - LDAP_READONLY_USER=false
      - LDAP_RFC2307BIS_SCHEMA=false
      - LDAP_BACKEND=mdb
      - LDAP_REPLICATION=false
      - KEEP_EXISTING_CONFIG=false
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - LDAP_SSL_HELPER_PREFIX=ldap
    volumes:
      - ${VOLUMES_DIR}/ldap:/var/lib/ldap
      - ${VOLUMES_DIR}/slapd.d:/etc/ldap/slapd.d
    networks:
      - ldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: unless-stopped
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - ldap
    networks:
      - ldap
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.phpldapadmin.entrypoints=websecure
      - traefik.http.routers.phpldapadmin.rule=Host(`pla.${DOMAINNAME}`)

networks:
  ldap:
    name: ldap
  traefik:
    name: traefik
    external: true
